apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gw.fullname" . }}-log
  labels:
    {{- include "gw.cm.labels" . | nindent 4 }}
data:
  qlog.json: |-
    {
      "endpoints": [
        "fd://stdout"
      ],
      "formatMode": "json",
      "routings": {
        "DEFAULT": "INFO"
      }
    }
