apiVersion: v1
kind: Service
metadata:
  name: {{ include "gw.fullname" . }}-rc
  {{- with .Values.dbsRc.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "gw.rc.labels" . | nindent 4 }}
    app: {{ include "gw.fullname" . }}-rc
spec:
  type: {{ .Values.dbsRc.service.type }}
  ports:
    - name: rc-qipc
      port: {{ .Values.dbsRc.service.port }}
      targetPort: {{ .Values.dbsRc.service.port }}
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: rc-metrics
  selector:
    {{- include "gw.rc.selectorLabels" . | nindent 4 }}
